name = "Vaka"
license = "MIT"
licenselink = "https://github.com/oneleaftea/vaka/blob/master/LICENSE.md"
description = "A minimal blog theme powered by Hugo"
homepage = "https://github.com/oneleaftea/vaka"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Yudy Chen"
  homepage = "https://thechens.org/"
