baseURL = "https://example.com/"
languageCode = "en-us"
title = "Vaka"
theme = "vaka"
disqusShortname = "username" # delete this to disable disqus comments
paginate = "5"

[permalinks]
    post = "/post/:slug/"

[params]
    author = "Yudy Chen"
    description = "A minimal Hugo theme"
    accent = "#008fcc"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = -100

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = -50

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = -25

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/username/"
    name = "facebook"
    weight = 5

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
